# Insert block_config here

blocked_websites = [
    "youtube.com",
    "www.youtube.com",
    "m.youtube.com",
    "youtu.be",
    "youtube-nocookie.com",
    "www.youtube-nocookie.com",
]

# Days of week to block where  Monday == 0 ... Sunday == 6
block_days = [
  0,
  1,
  2,
  3,
  4,
]

# List of times that should be blocked

[[block_schedule]]
start = 9
end = 12

[[block_schedule]]
start = 13
end = 18

[[block_schedule]]
start = 23
end = 24

[[block_schedule]]
start = 0
end = 5